# This is a basic workflow to help you get started with Actions
name: build and deploy

# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Build the angular app
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./matraum-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --prod
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: ./matraum-app/dist/matraum-app
          
  # deploy the app via FTP
  FTP-Deploy-Action:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    needs: build
    steps:
   
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
   
    - name: Download build
      uses: actions/download-artifact@v1
      with:
       name: deploy_dist
   
    - name: add git-ftp-args
      run:  echo "!." > .git-ftp-include
         
    - name: Deploy 
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.zh11.ch/
        ftp-username: web364f3
        ftp-password: ${{ secrets.FTP_PASSWORD }}
